let books = [
    "Action",
    "Adventure",
    "Anthology",
    "Autobiography",
    "Biography",
    "Children's",
    "Classics",
    "Comic Book",
    "Coming-of-Age",
    "Crime",
    "Drama",
    "Dystopian",
    "Fairy Tale",
    "Fantasy",
    "Graphic Novel",
    "Historical Fiction",
    "Horror",
    "Humor",
    "Literary Fiction",
    "Magical Realism",
    "Mystery",
    "Non-Fiction",
    "Paranormal",
    "Philosophical",
    "Poetry",
    "Political",
    "Romance",
    "Satire",
    "Science Fiction",
    "Short Story",
    "Suspense",
    "Thriller",
    "Travel",
    "True Crime",
    "Urban Fantasy",
    "Young Adult"
]
export { books };
